version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            virtualenv -p python3 /usr/local/share/virtualenvs/tap-uservoice
            source /usr/local/share/virtualenvs/tap-uservoice/bin/activate
            pip install .
            pip install pylint
            pylint tap_uservoice -d missing-docstring,invalid-name,line-too-long,too-many-locals,too-few-public-methods,fixme,stop-iteration-return,too-many-branches,useless-import-alias,no-else-return,logging-format-interpolation,broad-except,attribute-defined-outside-init,too-many-arguments,invalid-all-object,unused-argument,no-self-use,no-member,assignment-from-no-return,len-as-condition,duplicate-code
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-uservoice/bin/activate
            pip install nose
            nosetests
      - add_ssh_keys
      - run:
          name: 'Integration Tests'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-a-test --tap=tap-uservoice \
                       --target=target-stitch \
                       --orchestrator=stitch-orchestrator \
                       --email=harrison+sandboxtest@stitchdata.com \
                       --password=$SANDBOX_PASSWORD \
                       --client-id=50 \
                       tap_tester.suites.uservoice
